apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baymax55/argocd-lab.git
    targetRevision: HEAD
    path: blog
  destination: 
    server: https://kubernetes.default.svc
    namespace: blog

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
